title: RoadPrice — Évolutions tarifaires
description: Suivi hebdomadaire des prix WeRoad (KPIs, variations, alertes)

remote_theme: pages-themes/cayman@v0.2.0

plugins:
  - jekyll-remote-theme
  # Tu peux garder feed/sitemap si tu veux
  # - jekyll-feed
  # - jekyll-sitemap

# 👇 Ajoute ceci
repository: miniroles-boop/roadprice

markdown: kramdown
kramdown:
  input: GFM
  hard_wrap: false

lang: fr
