title: RoadPrice — Évolutions tarifaires
description: Suivi hebdomadaire des prix WeRoad (KPIs, variations, alertes)

remote_theme: pages-themes/cayman@v0.2.0

plugins:
  - jekyll-remote-theme
  - jekyll-feed
  - jekyll-sitemap

markdown: kramdown
kramdown:
  input: GFM
  hard_wrap: false

lang: fr
