name: Cleanup Old Monitor Runs

on:
  workflow_dispatch: {}

permissions:
  actions: write
  contents: read

jobs:
  cleanup:
    runs-on: ubuntu-latest
    steps:
      - name: Delete old runs and artifacts for monitor workflow
        uses: actions/github-script@v7
        with:
          script: |
            const workflowFile = "weekly-prices.yml"; // fichier du workflow monitor
            const { owner, repo } = context.repo;

            // 1. Lister les runs du workflow
            const runs = await github.rest.actions.listWorkflowRuns({
              owner,
              repo,
              workflow_id: workflowFile,
              per_page: 50
            });

            for (const run of runs.data.workflow_runs) {
              if (run.id === context.runId) continue; // ignorer le run courant

              console.log(`Suppression du run #${run.id} (${run.head_branch}, status=${run.status})`);

              // 2. Supprimer les artefacts de ce run
              const arts = await github.rest.actions.listWorkflowRunArtifacts({
                owner, repo, run_id: run.id
              });
              for (const art of arts.data.artifacts) {
                console.log(` - Artifact ${art.name} (#${art.id})`);
                await github.rest.actions.deleteArtifact({
                  owner, repo, artifact_id: art.id
                });
              }

              // 3. Supprimer le run lui-même
              await github.rest.actions.deleteWorkflowRun({
                owner, repo, run_id: run.id
              });
            }
            console.log("Nettoyage terminé ✅");
