name: Weekly Prices Monitor

on:
  schedule:
    - cron: "0 * * * *"
  workflow_dispatch: {}

jobs:
  run:
    runs-on: ubuntu-latest
    permissions:
      contents: write   # pour commit auto

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python (with pip cache)
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
          cache: "pip"
          cache-dependency-path: requirements.txt

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run weekly monitor
        env:
          ALERT_PCT: "0.10"
          ALERT_EUR: "150"
          SAME_DATE_MIN_EUR: "5"
          WEROAD_TOKEN: ${{ secrets.WEROAD_TOKEN }}
        run: |
          python monitor.py --out weekly_report.xlsx --sqlite data/weroad.db

      - name: Build single-page dashboard (docs/index.md)
        run: python summarize.py

      - name: Commit dashboard
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "chore: update dashboard (docs/index.md)"
          file_pattern: docs/index.md

      # Artefacts (optionnel)
      - name: Upload Excel artifact
        uses: actions/upload-artifact@v4
        with:
          name: weekly_report
          path: weekly_report.xlsx
          retention-days: 30

      - name: Upload SQLite artifact
        uses: actions/upload-artifact@v4
        with:
          name: sqlite_snapshot
          path: data/weroad.db
          retention-days: 90
