name: Weekly Prices Monitor

on:
  schedule:
    # Chaque mardi à 05:00 UTC ≈ 07:00 Europe/Paris
    - cron: "0 5 * * 2"
  workflow_dispatch: {}  # déclenchement manuel possible

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: |
          pip install pandas pyarrow requests openpyxl

      - name: Run weekly monitor
        run: |
          python monitor.py --out weekly_report.xlsx --sqlite data/weroad.db

      - name: Upload Excel artifact
        uses: actions/upload-artifact@v4
        with:
          name: weekly_report
          path: weekly_report.xlsx
          retention-days: 30

      - name: Upload SQLite artifact
        uses: actions/upload-artifact@v4
        with:
          name: sqlite_snapshot
          path: data/weroad.db
          retention-days: 90
